language: node_js

node_js:
  - "6"

script: npm run coverage

addons:
    code_climate:
        repo_token: 11f5371fe64594838110bd0490386681fe1b8310ea7a9e3afc0335e9bef02c1b

after_script:
  - codeclimate-test-reporter < ./coverage/lcov.info